# Generated by Django 3.1.6 on 2022-04-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='click1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='click2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='timer',
            field=models.DateTimeField(default='2012-09-04 06:00:00.000000-08:00'),
        ),
        migrations.AddField(
            model_name='score',
            name='volume1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='volume2',
            field=models.FloatField(default=0),
        ),
    ]
